import { NextResponse } from "next/server"

// Comprehensive ICD-10 codes for primary care / behavioral health
const ICD10_CODES = [
  // Substance Use Disorders
  { code: "F11.10", description: "Opioid use disorder, uncomplicated" },
  { code: "F11.20", description: "Opioid dependence, uncomplicated" },
  { code: "F11.21", description: "Opioid dependence, in remission" },
  { code: "F11.23", description: "Opioid dependence with withdrawal" },
  { code: "F10.10", description: "Alcohol use disorder, uncomplicated" },
  { code: "F10.20", description: "Alcohol dependence, uncomplicated" },
  { code: "F10.21", description: "Alcohol dependence, in remission" },
  { code: "F10.22", description: "Alcohol dependence with intoxication" },
  { code: "F10.23", description: "Alcohol dependence with withdrawal" },
  { code: "F14.10", description: "Cocaine use disorder, uncomplicated" },
  { code: "F14.20", description: "Cocaine dependence, uncomplicated" },
  { code: "F15.10", description: "Stimulant use disorder, uncomplicated" },
  { code: "F12.10", description: "Cannabis use disorder, uncomplicated" },
  { code: "F12.20", description: "Cannabis dependence, uncomplicated" },
  { code: "F19.10", description: "Other psychoactive substance use disorder" },
  { code: "F17.210", description: "Nicotine dependence, cigarettes, uncomplicated" },
  { code: "F17.220", description: "Nicotine dependence, chewing tobacco" },

  // Mental Health - Mood Disorders
  { code: "F32.0", description: "Major depressive disorder, single episode, mild" },
  { code: "F32.1", description: "Major depressive disorder, single episode, moderate" },
  { code: "F32.2", description: "Major depressive disorder, single episode, severe" },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified" },
  { code: "F33.0", description: "Major depressive disorder, recurrent, mild" },
  { code: "F33.1", description: "Major depressive disorder, recurrent, moderate" },
  { code: "F33.2", description: "Major depressive disorder, recurrent, severe" },
  { code: "F33.9", description: "Major depressive disorder, recurrent, unspecified" },
  { code: "F31.0", description: "Bipolar disorder, current episode hypomanic" },
  { code: "F31.1", description: "Bipolar disorder, current episode manic without psychotic features" },
  { code: "F31.2", description: "Bipolar disorder, current episode manic severe with psychotic features" },
  { code: "F31.3", description: "Bipolar disorder, current episode depressed, mild or moderate" },
  { code: "F31.4", description: "Bipolar disorder, current episode depressed, severe" },
  { code: "F31.5", description: "Bipolar disorder, current episode depressed, severe with psychotic features" },
  { code: "F31.9", description: "Bipolar disorder, unspecified" },
  { code: "F34.1", description: "Persistent depressive disorder (dysthymia)" },
  { code: "F34.8", description: "Other specified persistent mood disorders" },

  // Mental Health - Anxiety Disorders
  { code: "F41.0", description: "Panic disorder" },
  { code: "F41.1", description: "Generalized anxiety disorder" },
  { code: "F41.9", description: "Anxiety disorder, unspecified" },
  { code: "F40.00", description: "Agoraphobia, unspecified" },
  { code: "F40.10", description: "Social phobia, unspecified" },
  { code: "F42.2", description: "Mixed obsessions and compulsions" },
  { code: "F43.10", description: "Post-traumatic stress disorder, unspecified" },
  { code: "F43.11", description: "Post-traumatic stress disorder, acute" },
  { code: "F43.12", description: "Post-traumatic stress disorder, chronic" },
  { code: "F43.20", description: "Adjustment disorder, unspecified" },
  { code: "F43.21", description: "Adjustment disorder with depressed mood" },
  { code: "F43.22", description: "Adjustment disorder with anxiety" },
  { code: "F43.23", description: "Adjustment disorder with mixed anxiety and depressed mood" },

  // Mental Health - Psychotic Disorders
  { code: "F20.9", description: "Schizophrenia, unspecified" },
  { code: "F20.0", description: "Paranoid schizophrenia" },
  { code: "F20.1", description: "Disorganized schizophrenia" },
  { code: "F25.0", description: "Schizoaffective disorder, bipolar type" },
  { code: "F25.1", description: "Schizoaffective disorder, depressive type" },
  { code: "F22", description: "Delusional disorder" },

  // Mental Health - Personality Disorders
  { code: "F60.3", description: "Borderline personality disorder" },
  { code: "F60.0", description: "Paranoid personality disorder" },
  { code: "F60.1", description: "Schizoid personality disorder" },
  { code: "F60.2", description: "Antisocial personality disorder" },
  { code: "F60.4", description: "Histrionic personality disorder" },
  { code: "F60.5", description: "Obsessive-compulsive personality disorder" },
  { code: "F60.6", description: "Avoidant personality disorder" },
  { code: "F60.7", description: "Dependent personality disorder" },

  // Mental Health - Neurodevelopmental Disorders
  { code: "F90.0", description: "ADHD, predominantly inattentive type" },
  { code: "F90.1", description: "ADHD, predominantly hyperactive type" },
  { code: "F90.2", description: "ADHD, combined type" },
  { code: "F90.9", description: "ADHD, unspecified type" },
  { code: "F84.0", description: "Autism spectrum disorder" },
  { code: "F81.0", description: "Specific learning disorder with impairment in reading" },
  { code: "F81.2", description: "Specific learning disorder with impairment in mathematics" },

  // Mental Health - Eating Disorders
  { code: "F50.00", description: "Anorexia nervosa, unspecified" },
  { code: "F50.01", description: "Anorexia nervosa, restricting type" },
  { code: "F50.02", description: "Anorexia nervosa, binge eating/purging type" },
  { code: "F50.2", description: "Bulimia nervosa" },
  { code: "F50.9", description: "Eating disorder, unspecified" },

  // Mental Health - Sleep Disorders
  { code: "F51.01", description: "Insomnia, unspecified" },
  { code: "F51.11", description: "Hypersomnolence disorder, unspecified" },
  { code: "G47.00", description: "Insomnia, unspecified" },
  { code: "G47.10", description: "Hypersomnia, unspecified" },
  { code: "G47.33", description: "Obstructive sleep apnea" },

  // Primary Care - Cardiovascular
  { code: "I10", description: "Essential (primary) hypertension" },
  { code: "I11.0", description: "Hypertensive heart disease with heart failure" },
  { code: "I11.9", description: "Hypertensive heart disease without heart failure" },
  { code: "I12.0", description: "Hypertensive chronic kidney disease with stage 5 chronic kidney disease" },
  { code: "I13.0", description: "Hypertensive heart and chronic kidney disease with heart failure" },
  { code: "I20.9", description: "Angina pectoris, unspecified" },
  { code: "I25.10", description: "Atherosclerotic heart disease of native coronary artery without angina pectoris" },
  { code: "I50.9", description: "Heart failure, unspecified" },
  { code: "I50.1", description: "Left ventricular failure" },
  { code: "I50.2", description: "Systolic heart failure" },
  { code: "I50.3", description: "Diastolic heart failure" },
  { code: "I50.4", description: "Combined systolic and diastolic heart failure" },
  { code: "I48.91", description: "Unspecified atrial fibrillation" },
  { code: "I49.9", description: "Cardiac arrhythmia, unspecified" },

  // Primary Care - Endocrine/Metabolic
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", description: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E11.21", description: "Type 2 diabetes mellitus with diabetic nephropathy" },
  { code: "E11.22", description: "Type 2 diabetes mellitus with diabetic chronic kidney disease" },
  { code: "E11.40", description: "Type 2 diabetes mellitus with diabetic neuropathy, unspecified" },
  { code: "E11.621", description: "Type 2 diabetes mellitus with foot ulcer" },
  { code: "E10.9", description: "Type 1 diabetes mellitus without complications" },
  { code: "E78.5", description: "Hyperlipidemia, unspecified" },
  { code: "E78.0", description: "Pure hypercholesterolemia" },
  { code: "E78.1", description: "Pure hyperglyceridemia" },
  { code: "E78.2", description: "Mixed hyperlipidemia" },
  { code: "E78.4", description: "Other hyperlipidemia" },
  { code: "E03.9", description: "Hypothyroidism, unspecified" },
  { code: "E05.90", description: "Thyrotoxicosis, unspecified without thyrotoxic crisis or storm" },
  { code: "E87.6", description: "Hypokalemia" },
  { code: "E87.5", description: "Hyperkalemia" },

  // Primary Care - Respiratory
  { code: "J45.20", description: "Mild intermittent asthma, uncomplicated" },
  { code: "J45.30", description: "Mild persistent asthma, uncomplicated" },
  { code: "J45.40", description: "Moderate persistent asthma, uncomplicated" },
  { code: "J45.50", description: "Severe persistent asthma, uncomplicated" },
  { code: "J45.901", description: "Unspecified asthma with (acute) exacerbation" },
  { code: "J44.9", description: "Chronic obstructive pulmonary disease, unspecified" },
  { code: "J44.0", description: "Chronic obstructive pulmonary disease with acute lower respiratory infection" },
  { code: "J44.1", description: "Chronic obstructive pulmonary disease with (acute) exacerbation" },
  { code: "J06.9", description: "Acute upper respiratory infection, unspecified" },
  { code: "J00", description: "Acute nasopharyngitis (common cold)" },
  { code: "J02.9", description: "Acute pharyngitis, unspecified" },
  { code: "J03.90", description: "Acute tonsillitis, unspecified" },
  { code: "J04.0", description: "Acute laryngitis" },
  { code: "J15.9", description: "Unspecified bacterial pneumonia" },
  { code: "J18.9", description: "Pneumonia, unspecified organism" },
  { code: "J96.00", description: "Acute respiratory failure, unspecified whether with hypoxia or hypercapnia" },

  // Primary Care - Gastrointestinal
  { code: "K21.0", description: "Gastro-esophageal reflux disease with esophagitis" },
  { code: "K21.9", description: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K25.9", description: "Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation" },
  { code: "K29.30", description: "Chronic gastritis, unspecified, without bleeding" },
  { code: "K59.00", description: "Constipation, unspecified" },
  { code: "K59.01", description: "Slow transit constipation" },
  { code: "K59.09", description: "Other constipation" },
  { code: "K92.2", description: "Gastrointestinal hemorrhage, unspecified" },
  { code: "K92.1", description: "Melena" },
  { code: "R19.7", description: "Diarrhea, unspecified" },
  { code: "R10.9", description: "Unspecified abdominal pain" },
  { code: "R10.10", description: "Upper abdominal pain, unspecified" },
  { code: "R10.11", description: "Right upper quadrant pain" },
  { code: "R10.12", description: "Left upper quadrant pain" },
  { code: "R10.13", description: "Epigastric pain" },
  { code: "R10.30", description: "Lower abdominal pain, unspecified" },
  { code: "R10.31", description: "Right lower quadrant pain" },
  { code: "R10.32", description: "Left lower quadrant pain" },
  { code: "R10.33", description: "Periumbilical pain" },

  // Primary Care - Musculoskeletal
  { code: "M54.5", description: "Low back pain" },
  { code: "M54.2", description: "Cervicalgia (neck pain)" },
  { code: "M54.6", description: "Pain in thoracic spine" },
  { code: "M54.9", description: "Dorsalgia, unspecified" },
  { code: "M79.3", description: "Panniculitis, unspecified" },
  { code: "M25.561", description: "Pain in right knee" },
  { code: "M25.562", description: "Pain in left knee" },
  { code: "M25.551", description: "Pain in right hip" },
  { code: "M25.552", description: "Pain in left hip" },
  { code: "M25.511", description: "Pain in right shoulder" },
  { code: "M25.512", description: "Pain in left shoulder" },
  { code: "M79.3", description: "Panniculitis, unspecified" },
  { code: "M79.89", description: "Other specified soft tissue disorders" },
  { code: "M25.50", description: "Pain in unspecified joint" },
  { code: "M79.10", description: "Myalgia, unspecified site" },
  { code: "M79.3", description: "Panniculitis, unspecified" },

  // Primary Care - Neurological
  { code: "G43.909", description: "Migraine, unspecified, not intractable" },
  { code: "G43.919", description: "Migraine, unspecified, intractable" },
  { code: "G43.109", description: "Migraine without aura, not intractable" },
  { code: "G43.119", description: "Migraine without aura, intractable" },
  { code: "G44.1", description: "Vascular headache, not elsewhere classified" },
  { code: "G44.209", description: "Tension-type headache, unspecified, not intractable" },
  { code: "G93.1", description: "Anoxic brain damage, not elsewhere classified" },
  { code: "G89.29", description: "Other chronic pain" },
  { code: "G89.4", description: "Chronic pain syndrome" },
  { code: "G89.21", description: "Chronic pain due to trauma" },
  { code: "G89.22", description: "Chronic post-surgical pain" },
  { code: "G90.9", description: "Disorder of the autonomic nervous system, unspecified" },
  { code: "G93.40", description: "Encephalopathy, unspecified" },

  // Primary Care - Genitourinary
  { code: "N39.0", description: "Urinary tract infection, site not specified" },
  { code: "N30.00", description: "Acute cystitis without hematuria" },
  { code: "N30.01", description: "Acute cystitis with hematuria" },
  { code: "N30.90", description: "Cystitis, unspecified without hematuria" },
  { code: "N40.1", description: "Benign prostatic hyperplasia with lower urinary tract symptoms" },
  { code: "N40.0", description: "Benign prostatic hyperplasia without lower urinary tract symptoms" },
  { code: "N18.6", description: "End stage renal disease" },
  { code: "N18.9", description: "Chronic kidney disease, unspecified" },
  { code: "N18.30", description: "Chronic kidney disease, stage 3 unspecified" },
  { code: "N18.31", description: "Chronic kidney disease, stage 3a" },
  { code: "N18.32", description: "Chronic kidney disease, stage 3b" },
  { code: "N18.4", description: "Chronic kidney disease, stage 4" },
  { code: "N18.5", description: "Chronic kidney disease, stage 5" },
  { code: "N13.9", description: "Obstructive and reflux uropathy, unspecified" },

  // Primary Care - Dermatological
  { code: "L70.9", description: "Acne, unspecified" },
  { code: "L70.0", description: "Acne vulgaris" },
  { code: "L50.9", description: "Urticaria, unspecified" },
  { code: "L20.9", description: "Atopic dermatitis, unspecified" },
  { code: "L71.9", description: "Rosacea, unspecified" },
  { code: "L30.9", description: "Dermatitis, unspecified" },
  { code: "L08.9", description: "Local infection of skin and subcutaneous tissue, unspecified" },
  { code: "L03.90", description: "Cellulitis, unspecified" },
  { code: "L03.119", description: "Cellulitis of right upper limb" },
  { code: "L03.129", description: "Cellulitis of left upper limb" },
  { code: "L03.116", description: "Cellulitis of right lower limb" },
  { code: "L03.126", description: "Cellulitis of left lower limb" },

  // Primary Care - Infectious Diseases
  { code: "B34.9", description: "Viral infection, unspecified" },
  { code: "B00.9", description: "Herpesviral infection, unspecified" },
  { code: "B02.9", description: "Zoster without complications" },
  { code: "A49.9", description: "Bacterial infection, unspecified site" },
  { code: "A08.4", description: "Viral intestinal infection, unspecified" },
  { code: "B20", description: "Human immunodeficiency virus (HIV) disease" },
  { code: "Z21", description: "Asymptomatic human immunodeficiency virus (HIV) infection status" },

  // Primary Care - Obesity and Weight
  { code: "E66.9", description: "Obesity, unspecified" },
  { code: "E66.01", description: "Morbid (severe) obesity due to excess calories" },
  { code: "E66.09", description: "Other obesity due to excess calories" },
  { code: "E66.3", description: "Overweight" },
  { code: "E66.8", description: "Other obesity" },

  // Primary Care - Symptoms and Signs
  { code: "R05", description: "Cough" },
  { code: "R51", description: "Headache" },
  { code: "R50.9", description: "Fever, unspecified" },
  { code: "R06.02", description: "Shortness of breath" },
  { code: "R06.00", description: "Dyspnea, unspecified" },
  { code: "R53.83", description: "Other fatigue" },
  { code: "R53.1", description: "Weakness" },
  { code: "R42", description: "Dizziness and giddiness" },
  { code: "R11.0", description: "Nausea" },
  { code: "R11.2", description: "Nausea with vomiting, unspecified" },
  { code: "R06.09", description: "Other forms of dyspnea" },
  { code: "R50.81", description: "Fever presenting with conditions classified elsewhere" },
  { code: "R06.82", description: "Tachypnea, not elsewhere classified" },
  { code: "R94.31", description: "Abnormal electrocardiogram (ECG)" },
  { code: "R73.09", description: "Other abnormal glucose" },
  { code: "R79.9", description: "Abnormal finding of blood chemistry, unspecified" },
  { code: "R94.0", description: "Abnormal results of function studies of central nervous system" },

  // Preventive / Wellness
  { code: "Z00.00", description: "Encounter for general adult medical exam without abnormal findings" },
  { code: "Z00.01", description: "Encounter for general adult medical exam with abnormal findings" },
  { code: "Z00.121", description: "Encounter for routine child health examination with abnormal findings" },
  { code: "Z00.129", description: "Encounter for routine child health examination without abnormal findings" },
  { code: "Z23", description: "Encounter for immunization" },
  { code: "Z71.3", description: "Dietary counseling and surveillance" },
  { code: "Z71.82", description: "Exercise counseling" },
  { code: "Z87.891", description: "Personal history of nicotine dependence" },
  { code: "Z87.890", description: "Personal history of other specified diseases" },
  { code: "Z13.9", description: "Encounter for screening, unspecified" },
  { code: "Z13.6", description: "Encounter for screening for cardiovascular disorders" },
  { code: "Z13.79", description: "Encounter for screening for other disorder" },
  { code: "Z13.228", description: "Encounter for screening for other metabolic disorder" },
  { code: "Z51.11", description: "Encounter for antineoplastic chemotherapy" },
  { code: "Z51.81", description: "Encounter for therapeutic drug level monitoring" },

  // Pain Management
  { code: "G89.29", description: "Other chronic pain" },
  { code: "G89.4", description: "Chronic pain syndrome" },
  { code: "R52", description: "Pain, unspecified" },
  { code: "R52.1", description: "Acute pain" },
  { code: "R52.2", description: "Chronic pain" },
  { code: "R52.9", description: "Pain, unspecified" },

  // Social Determinants of Health
  { code: "Z59.0", description: "Homelessness" },
  { code: "Z59.1", description: "Inadequate housing" },
  { code: "Z59.2", description: "Discord with neighbors, lodgers, or landlord" },
  { code: "Z59.3", description: "Problems related to living in residential institution" },
  { code: "Z59.4", description: "Lack of adequate food and safe drinking water" },
  { code: "Z59.5", description: "Extreme poverty" },
  { code: "Z59.6", description: "Low income" },
  { code: "Z59.7", description: "Insufficient social insurance and welfare support" },
  { code: "Z59.81", description: "Transportation insecurity" },
  { code: "Z59.82", description: "Material hardship" },
  { code: "Z60.0", description: "Problems of adjustment to life-cycle transitions" },
  { code: "Z60.2", description: "Problems related to living alone" },
  { code: "Z60.3", description: "Acculturation difficulty" },
  { code: "Z60.4", description: "Social exclusion and rejection" },
  { code: "Z60.5", description: "Target of (perceived) adverse discrimination and persecution" },
  { code: "Z63.0", description: "Problems in relationship with spouse or partner" },
  { code: "Z63.1", description: "Problems in relationship with parents and in-laws" },
  { code: "Z63.4", description: "Disappearance and death of family member" },
  { code: "Z63.6", description: "Dependent relative needing care at home" },
  { code: "Z63.72", description: "Stress on family due to return of family member from military deployment" },
  { code: "Z63.8", description: "Other specified problems related to primary support group" },
  { code: "Z64.0", description: "Problems related to unwanted pregnancy" },
  { code: "Z64.1", description: "Problems related to multiparity" },
  { code: "Z65.0", description: "Conviction in civil or criminal proceedings without imprisonment" },
  { code: "Z65.1", description: "Imprisonment and other incarceration" },
  { code: "Z65.2", description: "Problems related to release from prison" },
  { code: "Z65.3", description: "Problems related to other legal circumstances" },
  { code: "Z65.4", description: "Victim of crime and terrorism" },
  { code: "Z65.5", description: "Exposure to disaster, war and other hostilities" },
  { code: "Z65.8", description: "Other specified problems related to psychosocial circumstances" },
  { code: "Z65.9", description: "Problem related to unspecified psychosocial circumstances" },
  { code: "Z72.0", description: "Tobacco use" },
  { code: "Z72.1", description: "Alcohol use" },
  { code: "Z72.2", description: "Drug use" },
  { code: "Z72.3", description: "Lack of physical exercise" },
  { code: "Z72.4", description: "Inappropriate diet and eating habits" },
  { code: "Z72.51", description: "High risk sexual behavior" },
  { code: "Z72.52", description: "High risk heterosexual behavior" },
  { code: "Z72.53", description: "High risk homosexual behavior" },
  { code: "Z72.59", description: "Other high risk sexual behavior" },
  { code: "Z72.6", description: "Gambling and betting" },
  { code: "Z72.9", description: "Problem related to lifestyle, unspecified" },
  { code: "Z73.0", description: "Burn-out" },
  { code: "Z73.2", description: "Lack of relaxation and leisure" },
  { code: "Z73.3", description: "Stress, not elsewhere classified" },
  { code: "Z73.4", description: "Inadequate social skills, not elsewhere classified" },
  { code: "Z73.5", description: "Social role conflict, unspecified" },
  { code: "Z73.6", description: "Limitation of activities due to disability" },
  { code: "Z73.8", description: "Other problems related to life management difficulty" },
  { code: "Z73.9", description: "Problem related to life management difficulty, unspecified" },
  { code: "Z74.01", description: "Bed confinement status" },
  { code: "Z74.09", description: "Other reduced mobility" },
  { code: "Z74.1", description: "Need for assistance with personal care" },
  { code: "Z74.2", description: "Need for assistance at home and no other household member able to render care" },
  { code: "Z74.3", description: "Need for continuous supervision" },
  { code: "Z74.8", description: "Other problems related to care provider dependency" },
  { code: "Z74.9", description: "Problem related to care provider dependency, unspecified" },
  { code: "Z75.0", description: "Unavailability of medical facilities in the home area" },
  { code: "Z75.1", description: "Person awaiting admission to adequate facility elsewhere" },
  { code: "Z75.2", description: "Other waiting period for investigation and treatment" },
  { code: "Z75.3", description: "Unavailability and inaccessibility of health care facilities" },
  { code: "Z75.4", description: "Unavailability and inaccessibility of other helping agencies" },
  { code: "Z75.5", description: "Holiday relief care" },
  { code: "Z75.8", description: "Other problems related to medical facilities and other health care" },
  { code: "Z75.9", description: "Unspecified problem related to medical facilities and other health care" },
  { code: "Z76.0", description: "Encounter for issue of repeat prescription" },
  { code: "Z76.1", description: "Encounter for health supervision and care of foundling" },
  { code: "Z76.2", description: "Encounter for health supervision and care of other healthy infant and child" },
  { code: "Z76.3", description: "Healthy person accompanying sick person" },
  { code: "Z76.4", description: "Other boarder in health care facility" },
  { code: "Z76.5", description: "Malingerer (conscious simulation)" },
  { code: "Z76.8", description: "Persons encountering health services in other specified circumstances" },
  { code: "Z76.9", description: "Person encountering health services in unspecified circumstances" },
  { code: "Z77.110", description: "Contact with and (suspected) exposure to air pollution" },
  { code: "Z77.120", description: "Contact with and (suspected) exposure to mold" },
  { code: "Z77.21", description: "Contact with and (suspected) exposure to potentially hazardous body fluids" },
  { code: "Z77.29", description: "Contact with and (suspected) exposure to other potentially hazardous chemicals" },
  { code: "Z77.9", description: "Contact with and (suspected) exposure to unspecified hazardous substance" },
  { code: "Z78.0", description: "Asymptomatic menopausal state" },
  { code: "Z78.1", description: "Physical restraint status" },
  { code: "Z78.9", description: "Other specified health status" },
  { code: "Z79.01", description: "Long term (current) use of anticoagulants" },
  { code: "Z79.1", description: "Long term (current) use of non-steroidal anti-inflammatory drugs (NSAID)" },
  { code: "Z79.2", description: "Long term (current) use of antibiotics" },
  { code: "Z79.3", description: "Long term (current) use of hormonal contraceptives" },
  { code: "Z79.4", description: "Long term (current) use of insulin" },
  { code: "Z79.51", description: "Long term (current) use of inhaled steroids" },
  { code: "Z79.52", description: "Long term (current) use of systemic steroids" },
  { code: "Z79.82", description: "Long term (current) use of aspirin" },
  { code: "Z79.83", description: "Long term (current) use of other non-steroidal anti-inflammatory drugs (NSAID)" },
  { code: "Z79.84", description: "Long term (current) use of oral hypoglycemic drugs" },
  { code: "Z79.891", description: "Long term (current) use of opiate analgesic" },
  { code: "Z79.899", description: "Other long term (current) drug therapy" },
  { code: "Z80.0", description: "Family history of malignant neoplasm of digestive organs" },
  { code: "Z80.3", description: "Family history of malignant neoplasm of breast" },
  { code: "Z80.41", description: "Family history of malignant neoplasm of ovary" },
  { code: "Z80.49", description: "Family history of malignant neoplasm of other genital organs" },
  { code: "Z80.51", description: "Family history of malignant neoplasm of prostate" },
  { code: "Z80.8", description: "Family history of malignant neoplasm of other organs or systems" },
  { code: "Z81.0", description: "Family history of intellectual disabilities" },
  { code: "Z81.1", description: "Family history of alcohol abuse and dependence" },
  { code: "Z81.2", description: "Family history of tobacco abuse and dependence" },
  { code: "Z81.3", description: "Family history of other psychoactive substance abuse and dependence" },
  { code: "Z81.8", description: "Family history of other mental and behavioral disorders" },
  { code: "Z82.0", description: "Family history of epilepsy and other diseases of the nervous system" },
  { code: "Z82.1", description: "Family history of blindness and visual loss" },
  { code: "Z82.2", description: "Family history of deafness and hearing loss" },
  { code: "Z82.3", description: "Family history of stroke" },
  { code: "Z82.4", description: "Family history of ischemic heart disease and other diseases of the circulatory system" },
  { code: "Z82.49", description: "Family history of other diseases of the circulatory system" },
  { code: "Z82.6", description: "Family history of arthritis and other diseases of the musculoskeletal system and connective tissue" },
  { code: "Z82.7", description: "Family history of diseases of the genitourinary system" },
  { code: "Z82.8", description: "Family history of other specific disabilities" },
  { code: "Z83.0", description: "Family history of human immunodeficiency virus (HIV) disease" },
  { code: "Z83.1", description: "Family history of other infectious and parasitic diseases" },
  { code: "Z83.2", description: "Family history of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism" },
  { code: "Z83.3", description: "Family history of diabetes mellitus" },
  { code: "Z83.4", description: "Family history of other endocrine, nutritional and metabolic diseases" },
  { code: "Z83.5", description: "Family history of other disorders of kidney and ureter" },
  { code: "Z83.6", description: "Family history of diseases of the respiratory system" },
  { code: "Z83.7", description: "Family history of diseases of the digestive system" },
  { code: "Z84.0", description: "Family history of diseases of the skin and subcutaneous tissue" },
  { code: "Z84.1", description: "Family history of disorders of kidney and ureter" },
  { code: "Z84.2", description: "Family history of other specified conditions" },
  { code: "Z84.3", description: "Family history of consanguinity" },
  { code: "Z84.81", description: "Family history of carrier of genetic disease" },
  { code: "Z84.89", description: "Family history of other specified conditions" },
  { code: "Z85.0", description: "Personal history of malignant neoplasm of digestive organs" },
  { code: "Z85.1", description: "Personal history of malignant neoplasm of trachea, bronchus and lung" },
  { code: "Z85.2", description: "Personal history of malignant neoplasm of other respiratory and intrathoracic organs" },
  { code: "Z85.3", description: "Personal history of malignant neoplasm of breast" },
  { code: "Z85.4", description: "Personal history of malignant neoplasm of genital organs" },
  { code: "Z85.5", description: "Personal history of malignant neoplasm of urinary tract" },
  { code: "Z85.6", description: "Personal history of leukemia" },
  { code: "Z85.7", description: "Personal history of other malignant neoplasms of lymphoid, hematopoietic and related tissues" },
  { code: "Z85.8", description: "Personal history of malignant neoplasms of other organs and systems" },
  { code: "Z85.9", description: "Personal history of malignant neoplasm, unspecified" },
  { code: "Z86.0", description: "Personal history of other neoplasms" },
  { code: "Z86.1", description: "Personal history of infectious and parasitic diseases" },
  { code: "Z86.11", description: "Personal history of tuberculosis" },
  { code: "Z86.2", description: "Personal history of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism" },
  { code: "Z86.3", description: "Personal history of endocrine, nutritional and metabolic diseases" },
  { code: "Z86.31", description: "Personal history of pneumonia" },
  { code: "Z86.32", description: "Personal history of other specified diseases" },
  { code: "Z86.4", description: "Personal history of psychoactive substance abuse" },
  { code: "Z86.5", description: "Personal history of injury, poisoning, toxic effect or other external cause" },
  { code: "Z86.51", description: "Personal history of traumatic brain injury" },
  { code: "Z86.52", description: "Personal history of other specified injuries" },
  { code: "Z86.59", description: "Personal history of other specified injuries" },
  { code: "Z86.6", description: "Personal history of (corrected) congenital malformations" },
  { code: "Z86.7", description: "Personal history of (corrected) congenital malformations of heart and circulatory system" },
  { code: "Z86.8", description: "Personal history of other specified conditions" },
  { code: "Z86.9", description: "Personal history of certain other diseases" },
  { code: "Z87.0", description: "Personal history of diseases of the respiratory system" },
  { code: "Z87.1", description: "Personal history of diseases of the digestive system" },
  { code: "Z87.2", description: "Personal history of diseases of the skin and subcutaneous tissue" },
  { code: "Z87.3", description: "Personal history of diseases of the musculoskeletal system and connective tissue" },
  { code: "Z87.4", description: "Personal history of diseases of the genitourinary system" },
  { code: "Z87.5", description: "Personal history of other diseases" },
  { code: "Z87.6", description: "Personal history of (healed) physical injury" },
  { code: "Z87.7", description: "Personal history of (healed) poisoning" },
  { code: "Z87.81", description: "Personal history of (healed) foreign body fully removed" },
  { code: "Z87.82", description: "Personal history of (healed) traumatic brain injury" },
  { code: "Z87.83", description: "Personal history of (healed) traumatic fracture" },
  { code: "Z87.89", description: "Personal history of other (healed) physical injuries and conditions" },
  { code: "Z87.890", description: "Personal history of other specified diseases" },
  { code: "Z87.891", description: "Personal history of nicotine dependence" },
  { code: "Z88.0", description: "Allergy status to penicillin" },
  { code: "Z88.1", description: "Allergy status to other antibiotic agents" },
  { code: "Z88.2", description: "Allergy status to sulfonamides" },
  { code: "Z88.3", description: "Allergy status to other anti-infective agents" },
  { code: "Z88.4", description: "Allergy status to anesthetic agent" },
  { code: "Z88.5", description: "Allergy status to narcotic agent" },
  { code: "Z88.6", description: "Allergy status to analgesic agent" },
  { code: "Z88.7", description: "Allergy status to serum and vaccine" },
  { code: "Z88.8", description: "Allergy status to other drugs, medicaments and biological substances" },
  { code: "Z88.9", description: "Allergy status to unspecified drugs, medicaments and biological substances" },
  { code: "Z89.0", description: "Acquired absence of thumb and finger" },
  { code: "Z89.1", description: "Acquired absence of hand and wrist" },
  { code: "Z89.2", description: "Acquired absence of upper limb above wrist" },
  { code: "Z89.3", description: "Acquired absence of both upper limbs (any level)" },
  { code: "Z89.4", description: "Acquired absence of foot and ankle" },
  { code: "Z89.5", description: "Acquired absence of leg at or below knee" },
  { code: "Z89.6", description: "Acquired absence of leg above knee" },
  { code: "Z89.7", description: "Acquired absence of both lower limbs (any level, except toes alone)" },
  { code: "Z89.9", description: "Acquired absence of limb, unspecified" },
  { code: "Z90.0", description: "Acquired absence of part of head and neck" },
  { code: "Z90.1", description: "Acquired absence of breast and nipple" },
  { code: "Z90.2", description: "Acquired absence of lung (part of)" },
  { code: "Z90.3", description: "Acquired absence of stomach (part of)" },
  { code: "Z90.4", description: "Acquired absence of other specified parts of digestive tract" },
  { code: "Z90.5", description: "Acquired absence of kidney" },
  { code: "Z90.6", description: "Acquired absence of other specified parts of urinary tract" },
  { code: "Z90.7", description: "Acquired absence of genital organ(s)" },
  { code: "Z90.8", description: "Acquired absence of other specified organs" },
  { code: "Z90.9", description: "Acquired absence of organ, unspecified" },
  { code: "Z91.0", description: "Patient's noncompliance with medical treatment and regimen" },
  { code: "Z91.1", description: "Patient's intentional underdosing of medication regimen" },
  { code: "Z91.12", description: "Patient's intentional underdosing of medication regimen due to financial hardship" },
  { code: "Z91.13", description: "Patient's intentional underdosing of medication regimen due to age-related debility" },
  { code: "Z91.14", description: "Patient's intentional underdosing of medication regimen due to other reason" },
  { code: "Z91.19", description: "Patient's intentional underdosing of medication regimen due to unspecified reason" },
  { code: "Z91.2", description: "Patient's unintentional underdosing of medication regimen" },
  { code: "Z91.3", description: "Wandering in diseases classified elsewhere" },
  { code: "Z91.4", description: "Personal history of psychological trauma, not elsewhere classified" },
  { code: "Z91.5", description: "Personal history of self-harm" },
  { code: "Z91.6", description: "Personal history of other physical trauma" },
  { code: "Z91.7", description: "Personal history of (corrected) congenital malformations" },
  { code: "Z91.8", description: "Other specified personal risk factors, not elsewhere classified" },
  { code: "Z91.81", description: "History of falling" },
  { code: "Z91.82", description: "Personal history of military deployment" },
  { code: "Z91.83", description: "Wandering in conditions classified elsewhere" },
  { code: "Z91.89", description: "Other specified personal risk factors, not elsewhere classified" },
  { code: "Z92.0", description: "Personal history of contraception" },
  { code: "Z92.1", description: "Personal history of antineoplastic chemotherapy" },
  { code: "Z92.2", description: "Personal history of antineoplastic radiation therapy" },
  { code: "Z92.3", description: "Personal history of other medical treatment" },
  { code: "Z92.4", description: "Personal history of psychological trauma, not elsewhere classified" },
  { code: "Z92.5", description: "Personal history of self-harm" },
  { code: "Z92.6", description: "Personal history of other physical trauma" },
  { code: "Z92.8", description: "Personal history of other specified conditions" },
  { code: "Z92.9", description: "Personal history of unspecified condition" },
  { code: "Z93.0", description: "Tracheostomy status" },
  { code: "Z93.1", description: "Gastrostomy status" },
  { code: "Z93.2", description: "Ileostomy status" },
  { code: "Z93.3", description: "Colostomy status" },
  { code: "Z93.4", description: "Other artificial opening of gastrointestinal tract status" },
  { code: "Z93.5", description: "Cystostomy status" },
  { code: "Z93.6", description: "Other artificial opening of urinary tract status" },
  { code: "Z93.8", description: "Other specified artificial opening status" },
  { code: "Z93.9", description: "Artificial opening status, unspecified" },
  { code: "Z94.0", description: "Kidney transplant status" },
  { code: "Z94.1", description: "Heart transplant status" },
  { code: "Z94.2", description: "Lung transplant status" },
  { code: "Z94.3", description: "Heart and lungs transplant status" },
  { code: "Z94.4", description: "Liver transplant status" },
  { code: "Z94.5", description: "Skin transplant status" },
  { code: "Z94.6", description: "Bone transplant status" },
  { code: "Z94.7", description: "Cornea transplant status" },
  { code: "Z94.8", description: "Other specified transplanted organ and tissue status" },
  { code: "Z94.9", description: "Transplanted organ and tissue status, unspecified" },
  { code: "Z95.0", description: "Presence of aortocoronary bypass graft" },
  { code: "Z95.1", description: "Presence of aortocoronary bypass graft with angina pectoris" },
  { code: "Z95.2", description: "Presence of prosthetic heart valve" },
  { code: "Z95.3", description: "Presence of xenogenic heart valve" },
  { code: "Z95.4", description: "Presence of other heart-valve replacement" },
  { code: "Z95.5", description: "Presence of coronary angioplasty implant and graft" },
  { code: "Z95.8", description: "Presence of other cardiac and vascular implants and grafts" },
  { code: "Z95.9", description: "Presence of cardiac and vascular implant and graft, unspecified" },
  { code: "Z96.0", description: "Presence of urogenital implants" },
  { code: "Z96.1", description: "Presence of intraocular lens" },
  { code: "Z96.2", description: "Presence of otological and audiological implants" },
  { code: "Z96.3", description: "Presence of artificial larynx" },
  { code: "Z96.4", description: "Presence of endocrine implants" },
  { code: "Z96.5", description: "Presence of tooth-root and mandibular implants" },
  { code: "Z96.6", description: "Presence of orthopedic joint implants" },
  { code: "Z96.61", description: "Presence of right artificial shoulder joint" },
  { code: "Z96.62", description: "Presence of left artificial shoulder joint" },
  { code: "Z96.63", description: "Presence of right artificial elbow joint" },
  { code: "Z96.64", description: "Presence of left artificial elbow joint" },
  { code: "Z96.641", description: "Presence of left artificial elbow joint" },
  { code: "Z96.65", description: "Presence of right artificial wrist joint" },
  { code: "Z96.66", description: "Presence of left artificial wrist joint" },
  { code: "Z96.67", description: "Presence of right artificial hip joint" },
  { code: "Z96.68", description: "Presence of left artificial hip joint" },
  { code: "Z96.69", description: "Presence of other specified artificial joint" },
  { code: "Z96.7", description: "Presence of other bone and tendon implants" },
  { code: "Z96.8", description: "Presence of other specified functional implants" },
  { code: "Z96.9", description: "Presence of functional implant, unspecified" },
  { code: "Z97.0", description: "Presence of artificial eye" },
  { code: "Z97.1", description: "Presence of artificial limb (complete) (partial)" },
  { code: "Z97.2", description: "Presence of dental prosthetic device (complete) (partial)" },
  { code: "Z97.3", description: "Presence of spectacles and contact lenses" },
  { code: "Z97.4", description: "Presence of external hearing-aid" },
  { code: "Z97.5", description: "Presence of (intrauterine) contraceptive device" },
  { code: "Z97.8", description: "Presence of other specified devices" },
  { code: "Z97.9", description: "Presence of other and unspecified devices" },
  { code: "Z98.0", description: "Intestinal bypass and anastomosis status" },
  { code: "Z98.1", description: "Arthrodesis status" },
  { code: "Z98.2", description: "Presence of cerebrospinal fluid drainage device" },
  { code: "Z98.3", description: "Post therapeutic collapse of lung status" },
  { code: "Z98.4", description: "Cataract extraction status" },
  { code: "Z98.5", description: "Presence of corneal transplant status" },
  { code: "Z98.6", description: "Presence of other postsurgical states" },
  { code: "Z98.7", description: "Presence of other postsurgical states" },
  { code: "Z98.8", description: "Other specified postprocedural states" },
  { code: "Z98.9", description: "Postprocedural state, unspecified" },
  { code: "Z99.0", description: "Dependence on aspirator" },
  { code: "Z99.1", description: "Dependence on respirator" },
  { code: "Z99.2", description: "Dependence on renal dialysis" },
  { code: "Z99.3", description: "Dependence on wheelchair" },
  { code: "Z99.4", description: "Dependence on artificial heart" },
  { code: "Z99.5", description: "Dependence on supplemental oxygen" },
  { code: "Z99.6", description: "Dependence on other enabling machines and devices" },
  { code: "Z99.7", description: "Dependence on other enabling machines and devices" },
  { code: "Z99.8", description: "Dependence on other enabling machines and devices" },
  { code: "Z99.9", description: "Dependence on enabling machine or device, unspecified" },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const query = searchParams.get("query")?.toLowerCase() || searchParams.get("q")?.toLowerCase() || ""

  let filteredCodes = ICD10_CODES

  if (query) {
    filteredCodes = ICD10_CODES.filter(
      (code) => code.code.toLowerCase().includes(query) || code.description.toLowerCase().includes(query),
    )
  }

  return NextResponse.json({ codes: filteredCodes.slice(0, 100) })
}
