import { createServiceClient } from "@/lib/supabase/service-role"
import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"

export async function GET(request: NextRequest) {
  try {
    const supabase = createServiceClient()

    // Fetch referrals with notes count
    // Use a simpler query first, then fetch notes separately if needed
    let referrals: any[] = []
    let referralsError: any = null

    try {
      const { data, error } = await supabase
        .from("community_referrals")
        .select("*")
        .order("submitted_at", { ascending: false })
        .limit(100)

      if (error) {
        referralsError = error
        console.error("[Community Outreach] Error fetching referrals:", error)
      } else {
        referrals = data || []
      }
    } catch (err) {
      console.error("[Community Outreach] Exception fetching referrals:", err)
      referralsError = err
    }

    // If referrals fetch failed, return empty array
    if (referralsError) {
      return NextResponse.json({ referrals: [] })
    }

    // Fetch notes count for each referral separately
    const referralsWithCount = await Promise.all(
      referrals.map(async (ref: any) => {
        let notesCount = 0
        try {
          const { count, error: notesError } = await supabase
            .from("community_referral_notes")
            .select("*", { count: "exact", head: true })
            .eq("referral_id", ref.id)

          if (!notesError && count !== null) {
            notesCount = count
          } else if (notesError) {
            console.error(`[Community Outreach] Error fetching notes for referral ${ref.id}:`, notesError)
          }
        } catch (err) {
          console.error(`[Community Outreach] Exception fetching notes for referral ${ref.id}:`, err)
        }

        return {
          ...ref,
          notes_count: notesCount,
          created_at: ref.submitted_at || ref.created_at, // Use submitted_at if available
        }
      })
    )

    return NextResponse.json({ referrals: referralsWithCount })
  } catch (error: any) {
    console.error("[Community Outreach] Error fetching referrals:", error)
    return NextResponse.json({ referrals: [] })
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = createServiceClient()
    const body = await request.json()

    const {
      referral_type,
      referrer_name,
      referrer_organization,
      referrer_title,
      referrer_email,
      referrer_phone,
      client_first_name,
      client_last_name,
      client_date_of_birth,
      client_email,
      client_phone,
      client_preferred_contact,
      client_preferred_time,
      client_address_city,
      client_address_state,
      client_address_zip,
      primary_concerns,
      additional_concerns,
      urgency_level,
      current_crisis,
      previous_treatment,
      previous_treatment_details,
      current_medications,
      insurance_type,
      insurance_provider,
      insurance_member_id,
      hipaa_acknowledged,
      consent_to_contact,
      consent_to_share_with_referrer,
      source_url,
      utm_source,
      utm_campaign,
    } = body

    // The referral_number will be auto-generated by the database trigger
    const { data: referral, error } = await supabase
      .from("community_referrals")
      .insert({
        referral_type,
        referrer_name,
        referrer_organization,
        referrer_title,
        referrer_email,
        referrer_phone,
        client_first_name,
        client_last_name,
        client_date_of_birth,
        client_email,
        client_phone,
        client_preferred_contact: client_preferred_contact || "phone",
        client_preferred_time,
        client_address_city,
        client_address_state,
        client_address_zip,
        primary_concerns: Array.isArray(primary_concerns) ? primary_concerns : [],
        additional_concerns,
        urgency_level: urgency_level || "routine",
        current_crisis: current_crisis || false,
        previous_treatment,
        previous_treatment_details,
        current_medications,
        insurance_type,
        insurance_provider,
        insurance_member_id,
        hipaa_acknowledged: hipaa_acknowledged || false,
        consent_to_contact: consent_to_contact || false,
        consent_to_share_with_referrer: consent_to_share_with_referrer || false,
        status: "new",
        source_url,
        utm_source,
        utm_campaign,
      })
      .select()
      .single()

    if (error) throw error

    return NextResponse.json({ referral })
  } catch (error: any) {
    console.error("[Community Outreach] Error creating referral:", error)
    return NextResponse.json({ error: "Failed to create referral" }, { status: 500 })
  }
}
